### ISSUE TITLE
Add import_measures as a final step

### ISSUE THREAD

**Issue by annapowellsmith** [ebmdatalab/openprescribing-data#1]
Calculating measures is part of the data import process each month, let's add it even though it's not strictly importing data.

**Comment by sebbacon** [comment]
Have opted for the `REFRESH MATERIALIZED VIEW CONCURRENTLY` option in the first instance, on the grounds that even if it takes ages, it shouldn't really matter. This probably depends on the definition of "ages". The documentation does state that concurrent updates will probably be slower for the types of queries we're doing. That said, the implementation sounds pretty much like what we were going to do manually anyway.

It seems like the tradeoff is between the operation completing quickly but preventing some kinds of queries from running successfully, and having the operation completing slowly but not breaking anything.

Given "quickly" already means > 18 hours (IIRC), then as long as slowly isn't, say, > 3 days, then this solution should be Good Enough.

I still think it's suspicious that it takes quite so long for the query to execute. If this performance is a problem we could either spend a couple of days on it ourselves, or perhaps get a postgres expert to help us analyze it.

**Comment by sebbacon** [comment]
Question: the current README says we should run:

```
python manage.py import_measures --start_date YYYY-MM-DD --end_date YYYY-MM-DD -v 2
```

I'm not clear what the correct values for `start_date` and `end_date` should be; the docs possibly suggest that measures are dependent on up-to-date list sizes. Does that mean this should be run quartlerly whenever list sizes are updated? Or monthly whenever prescribing data is updated? 

In other words, is there a particular dataset which, when updated, should trigger running this command? If it's the prescribing data, then I assume this command should just be run monthly for the month of data just imported? If it's the list size data, then quarterly for that quarter?

**Comment by annapowellsmith** [comment]
They should be imported monthly after the prescribing data, and after list size data has been imported too. The date params should be the same month.
